export const brand = [
  {
    id:0,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/1.jpg",
    title:"brand1"
  },
  {
    id:1,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/2.jpg",
    title:"brand1"
  },
  {
    id:2,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/3.jpg",
    title:"brand1"
  },
  {
    id:3,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/4.jpg",
    title:"brand1"
  },
  {
    id:4,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/5.jpg",
    title:"brand1"
  },
  {
    id:6,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/1.jpg",
    title:"brand1"
  },  
  {
    id:7,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/2.jpg",
    title:"brand1"
  },
  {
    id:8,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/1.jpg",
    title:"brand1"
  },
  {
    id:9,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/2.jpg",
    title:"brand1"
  },
  {
    id:10,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/3.jpg",
    title:"brand1"
  },
  {
    id:11,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/4.jpg",
    title:"brand1"
  },
  {
    id:12,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/5.jpg",
    title:"brand1"
  },
  {
    id:13,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/1.jpg",
    title:"brand1"
  },  
  {
    id:14,
    img:"https://htmldemo.net/looki/looki/assets/img/brand/2.jpg",
    title:"brand1"
  }, 
]